apiVersion: v1
kind      : ConfigMap
metadata  :
  name: redis-tester
data      :
  REDIS_HOST: master.xxxxxx.cache.amazonaws.com
  REDIS_PORT: '6379'
  REDIS_PASSWORD: xxxxxx
  REDIS_NODES: replica.xxxxxx.cache.amazonaws.com:6379
  REDIS_SSL: true
  REDIS_MODE: master_replica
  SERVER_PORT: 8080
---
apiVersion: apps/v1
kind      : Deployment
metadata  :
  name  : redis-tester
  labels:
    app: redis-tester
spec      :
  replicas: 1
  template:
    metadata:
      name  : redis-tester
      labels:
        app: redis-tester
    spec    :
      containers   :
        - name           : redis-tester
          image          : redis-tester:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: redis-tester
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis-tester
---
apiVersion: v1
kind      : Service
metadata  :
  name: redis-tester
spec      :
  selector:
    app: redis-tester
  ports   :
    - port: 8080
      targetPort: 8080
  type    : LoadBalancer

